<?php
namespace app\models;
use yii\db\ActiveRecord;

class Arcicle extends ActiveRecord
{
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }
}